# Demo: Homework 0

### Demo 1: Artificial Neural Network

Here we will realize the `Equivalence-function`:

**Function Definition:**

|  x1  |  x2  |  y  |
|:---:|:---:|:---:|
|0|0|1|
|0|1|-1|
|1|0|-1|
|1|1|1|

**Neural Network Architecture:**

_Input Layer Neurons:_ 2 \
_Hidden Layer 1 Neurons:_ 5 \
_Hidden Layer 2 Neurons:_ 5 \
_Output Layer Neurons:_ 1 \

_Hidden Layer Activation Function:_ ReLU \
_Output Layer Activation Function:_ sign \

In [ ]:
# Import necessary libraries
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split


In [ ]:
# Prepare training data
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [1, -1, -1, 1]

X = np.array(X)
y = np.array(y)

In [ ]:
# Define Neural Network According to the architecture
nn = MLPClassifier(random_state=1, max_iter=1000, hidden_layer_sizes=(5, 5), activation='relu', alpha=0.001, solver='lbfgs', verbose = True)

In [ ]:
# Train the model
trained_nn = nn.fit(X, y)

In [ ]:
# Test the model
trained_nn.predict([[0,0], [0, 1], [1, 0], [1, 1]])

array([ 1, -1, -1,  1])

In [ ]:
# Print weights
trained_nn.coefs_

[array([[ 0.0090549 ,  1.51590662,  0.0545496 ,  2.03893339,  0.03854747],
        [ 0.04448571, -1.51606807,  0.01685306, -2.03911612, -0.00423584]]),
 array([[-0.01556365,  0.00755006, -0.00535837,  0.03283261,  0.02756328],
        [ 0.17404971, -1.44587962,  0.02557346, -0.09420408,  1.84110888],
        [-0.03602752,  0.03788539,  0.04208422,  0.03014443, -0.03452435],
        [-2.28824107,  1.14639738,  0.08400236, -0.62463022,  1.61767344],
        [ 0.01684339, -0.0170275 , -0.03055127,  0.0439802 , -0.02283813]]),
 array([[-2.14461531],
        [ 1.77578242],
        [-0.011636  ],
        [-0.50409231],
        [-2.56714284]])]

### Demo 2: Logistic Regression

In [ ]:
# Here we are generating some random data
X, y = make_classification(n_samples=100, random_state=1)

In [ ]:
# Splitting Data into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1, test_size=0.2)

In [ ]:
# Define the model
logistic_regressor = LogisticRegression(random_state=0)

In [ ]:
# Train the model
trained_model = logistic_regressor.fit(X_train, y_train)

In [ ]:
# Make predictions
predictions = trained_model.predict(X_test)

In [ ]:
# Evaluate Model Performance
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       1.00      0.80      0.89        10

    accuracy                           0.90        20
   macro avg       0.92      0.90      0.90        20
weighted avg       0.92      0.90      0.90        20

